unlock_gate:
  fields:
    serial:
      required: true
      selector:
        text:
unlock_door:
  fields:
    serial:
      required: true
      selector:
        text:
set_video_encryption:
  fields:
    serial:
      required: false
      selector:
        text:
    enable:
      required: true
      selector:
        boolean:
    verification_code:
      required: true
      selector:
        text:
